### PR TITLE
Add package.json in order to get npm scripts

### PR DESCRIPTION
**Pull request by jasonkarns**
No matter how many times I pop into node-build to scrape node/io versions, I keep expected to just be able to do `npm run` and see the list of scripts.

This change adds a package.json (set to private so it doesn't get published to the registry). And adds a `scrape` script so the scraper can be invoked via `npm run scrape`.

### CODE REVIEW

**Comment by jawshooah** [comment]
:+1:

**Comment by xiamx** [comment]
Can we rename the command to something more meaningful like "update-versions"?

**Comment by jasonkarns** [comment]
per @xiamx, renamed the scraper script to `write-definitions` (and moved the scraper files into `script/`)

add npm-test as `script/test`
removed the s3-put script and related functions from script/

```
$ npm run
Lifecycle scripts included in node-build:
  test
    script/test

available via `npm run-script`:
  write-definitions
    script/write-definitions
```

Eventually, when the `release` and `brew-publish` scripts are working for us, we can add those to the package manifest

I think this is ready to merge

**Comment by jawshooah** [comment]
:+1: LGTM

**Pull request merged**
