### PR TITLE
Merge in updates from ruby-build upstream

### PR DESCRIPTION
**Pull request by jasonkarns**
Merges in changes from the following ruby-build releases:

- [v20130408](https://github.com/sstephenson/ruby-build/tree/v20130408)
- [v20130501](https://github.com/sstephenson/ruby-build/tree/v20130501)
- [v20130514](https://github.com/sstephenson/ruby-build/tree/v20130514)
- [v20130518](https://github.com/sstephenson/ruby-build/tree/v20130518)
- [v20130628](https://github.com/sstephenson/ruby-build/tree/v20130628)
- [v20130806](https://github.com/sstephenson/ruby-build/tree/v20130806)

and also merged:
- [v20130901](https://github.com/sstephenson/ruby-build/tree/v20130901)
- [v20130907](https://github.com/sstephenson/ruby-build/tree/v20130907)
- [v20130923](https://github.com/sstephenson/ruby-build/tree/v20130923)
- [v20131008](https://github.com/sstephenson/ruby-build/tree/v20131008)
- [v20131024](https://github.com/sstephenson/ruby-build/tree/v20131024)

### CODE REVIEW

**Comment by jasonkarns** [comment]
The tests will fail because ruby-build doesn't fix their own test suite from these changes until v20131024 which is another 5 releases from where I am after all these merges.

**Comment by jawshooah** [comment]
What's the difference between this and #52?

**Comment by jasonkarns** [comment]
I was hoping nobody would catch that. ;)

It's identical in its current form. This PR's branch (https://github.com/OiNutter/node-build/tree/updates-from-ruby-build) is currently pointing to the same commit as #52's (https://github.com/OiNutter/node-build/tree/ruby-build-v20130806)

I meant to push this branch (updates-from-ruby-build) so that I can continue to merge in ruby build releases and have them just continue to be added to this PR. Since we probably don't want to merge any of these until we're completely up to date with ruby-build, but at the same time want to be able to review the changes a bit at a time. Locally, I'm creating a branch for each ruby-build version merge, but I'm branching them sequentially so each successive merge builds on the previous merges. `updates-from-ruby-build` is just tracking the latest of these merges as I go.

**Comment by jasonkarns** [comment]
I merged in the next few sets of ruby-build releases so it's back to passing tests. I think this is a good checkpoint to review and make sure everyone is okay with the changes so far.

**Pull request merged**
