### PR TITLE
prefer to install binaries

### PR DESCRIPTION
**Pull request by jasonkarns**
It's already possible to install binaries using node-build with the following definition:

```
install_package node-v0.10.36-darwin-x64 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-darwin-x64.tar.gz" copy
```

Since the package name can be derived from the url, and distributions will always be installed via 'copy', I created a wrapper function `install_distro` which takes just the url (with optional checksum).

Now a definition file can do:

```
install_distro "http://nodejs.org/dist/v0.10.36/node-v0.10.36-darwin-x64.tar.gz#f5768eaabc692fd3ed0cb063d17962c933951b78dec09af3c30eb76c3189d9ee"
```

Of course, this makes the definition files platform-specific, so this doesn't really work in the general case. 
Here's my approach:

In the spirit of node-build, we don't want the components of a distribution URL to be pieced together automatically. This would couple node-build to the url structure of nodejs.org or iojs.org. This means we can't simply hack together URLs with the target platform/architecture and version number (which is what wfarr's nodenv-install does, and likely others).

So we need a way to have the definition files "tell" node-build what the package url is for a given platform. To that end, I've added the `distro` function, which is meant to be invoked with the platform/architecture and the url for that distribution.

```
distro darwin-x64 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-darwin-x64.tar.gz#f5768eaabc692fd3ed0cb063d17962c933951b78dec09af3c30eb76c3189d9ee"
```

A definition file, then, would invoke this multiple times for as many distributions as are available for the given node release. The `distro` function simply matches the given platform to the current platform. If there's a match, it saves the provided distro url as `DISTRO`.

Here's where it gets tricky. Since we would ideally like a single definition file to house the install commands for both binaries as well as from-source builds, we need to somehow provide a way to prevent the source build if the binary is available. And to also still allow a source-build if the binary install fails for whatever reason. So the flow is this:

1. definition file invokes `distro` for each available binary
2. if a provided distro matches the current platform, the distro url is saved as DISTRO
3. when `install_package` (or `install_git`, `install_svn`) is invoked, we first invoke `try_install_distro`
    - if DISTRO is not set (maybe no binary existed for current platform, or the definition file didn't include distros), then `try_install_distro` fails and `install_package_using` continues per usual
    - if DISTRO _is_ set, we unset it and invoke `install_distro` with the url
4. `install_distro` just calls back through to `install_package`, which again invokes `try_install_distro` which fails this time because DISTRO has been unset. So the package installation continues like a normal 'copy' install

Example definition file:

```
distro darwin-x64 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-darwin-x64.tar.gz#f5768eaabc692fd3ed0cb063d17962c933951b78dec09af3c30eb76c3189d9ee"
distro darwin-x86 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-darwin-x86.tar.gz#b0fe1dc7ed538b14c253de2d3b0bb49317126d0736855f5eed64a79ade99fe4e"
distro linux-x64 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x64.tar.gz#2bc13477684a9fe534bdc9d8f4a8caf6257a11953b57c42cad9b919ee259a0d5"
distro linux-x86 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x86.tar.gz#65edbf9d139ba572e1ed9e967b41ffee513a4fce0db600bc06b4184aa2111de2"
distro sunos-x64 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-sunos-x64.tar.gz#0b4edef67c9ace5f2846b465a26d225850416db7b5272066c08574f28ac15444"
distro sunos-x86 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-sunos-x86.tar.gz#8186cf8261d3135a3431cacd0de086c73774d99b27c0ab00110565653945ff06"

install_package "node-v0.10.36" "https://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz#b9d7d1d0294bce46686b13a05da6fc5b1e7743b597544aa888e8e64a9f178c81"
```

With this setup:
- there exists the `install_distro` function that definitions may use to just straight up install a binary with no platform checking
- a single version's definition file includes *both* binary install instructions as well as compilation commands
- definition files can list multiple binaries for various platforms
- distribution urls can still include checksums which are verified before installing
- missing distributions still fall back to a from-source build
- a failed distribution installation (checksum failure, etc) falls back to from-source build
- before/after install hooks are still run for binary installations

Thoughts?

TODO:
- [x] add a flag to force from-source build, skipping a binary if it exists (`--source` ? `--compile`? `--no-distro`? `--no-binary` ?)
- [x] update the scraper to add binary distros to existing definitions

### CODE REVIEW

**Comment by jasonkarns** [comment]
I would *really* appreciate it if some better shell hackers came up with a better way to handle this c339385. @OiNutter @ianks @charlesbjohnson ?

**Comment by jasonkarns** [comment]
I'm not terribly happy with this solution, but it works. The main issue is that the install_package_using function relies on errors being trapped; none of the invoked functions' status codes are checked through that process. It relies on errors being trapped by build_failed which then exits. Clearly, when we're attempting a binary install, we can't just exit if it fails (we want to attempt compilation in case of failure). So I modified the two critical invocations (the tarball download and fetch functions) to have their status codes guarded. This way the errors bubble up to `try_install_distro` (through `install_package_using` and `install_package`). On success, it just returns which skips compilation. On failure, it proceeds per usual to attempt compilation. (At this point, since the install_package_function is now no longer covered by a boolean `&&`, the error trapping works as usual.)

This is about as minimal a change as I could find to get binary support. Since bash doesn't have any proper exception handling (that would pop the stack), this is the best I could come up with (I would have even preferred `goto` if shell had it). Here's hoping @sstephenson, @mislav and crew find a cleaner way to do this with ruby-build that we can adopt in the future. I have a feeling it will require a more fundamental shift in how definition files are executed. (Perhaps in a subshell instead of sourced, which would allow `exit`)

I'll update the scraper/definitions to include all available binaries. Then we can let it bake a while as vNext or something. I'd like to have it released within a week or so, since people have been clamoring for binary installs for a while.

**Comment by xiamx** [comment]
WOWW This is super nice to have. Currently, building from source take about 15mins on my machines. 
For trapping binary installation failure and fallback to compilation part -- Perhaps it's not necessary. If we support installing binary for some distribution and it fails then it's fine to let user know.

**Comment by jasonkarns** [comment]
@xiamx removing the automatic fallback-to-compile does make the code a bit simpler. Here's a variant that simply errors out if the binary install fails: https://github.com/OiNutter/node-build/pull/76

It emits a helpful message to "try again with --compile flag". I rather like this approach now. It's less brittle, since we don't have to worry about manually bubbling up return codes (we surely won't bubble at *every* level). It keeps the user in charge (perhaps they *really* don't want to do a compile and would rather debug the binary install; or do a manual install). And worse case, we've emitted a message the makes it easy to force a compile, if they so choose.

**Comment by xiamx** [comment]
@jasonkarns Yup, in case binary install fail, it should either be that `node-build` has a bug, server that has the binary is unavailable or user is a victim of mitm attack (downloading via https, this should be extremely unlikely). Perhaps it's better to continue the behavior of compiling from source, and have `--binary` or similar flag to use binary distribution instead. This way we won't risk breaking users' workflow with regressions caused by this feature.

**Comment by jasonkarns** [comment]
I'd rather have this feature on by default. Assuming it works bug-free, it's definitely the desired default. (A *lot* of people have been clamoring for it.) And if there are bugs, the `--compile` flag gets back to old behavior (or reverting to an old revision as a last resort). If the end goal is agreed to be binary-by-default, I'd rather not do any sort of phased release (where it's opt-in for a while before becoming default). I think that would just lead to more confusion in people's workflows.

**Comment by jawshooah** [comment]
`nodenv install` appears to be both installing the binary *and* building from source with these changes:

```bash
$ git rev-parse --short HEAD
caeb94d

$ nodenv install 4.0.0
Downloading node-v4.0.0-darwin-x64.tar.gz...
-> https://nodejs.org/dist/v4.0.0/node-v4.0.0-darwin-x64.tar.gz
Installing node-v4.0.0-darwin-x64...
Installed node-v4.0.0-darwin-x64 to /Users/joshuahagins/.nodenv/versions/4.0.0

Downloading node-v4.0.0.tar.gz...
-> https://nodejs.org/dist/v4.0.0/node-v4.0.0.tar.gz
Installing node-v4.0.0...
Installed node-v4.0.0 to /Users/joshuahagins/.nodenv/versions/4.0.0
```

**Comment by jasonkarns** [comment]
@jawshooah forgot to ping (i always forget that pushing commits doesn't trigger notifications)

I fixed the double-install, and re-worked the code to be (hopefully) a bit less confusing. the recursive call is now easier to trace.

I'm cautiously happy with what we have now.

Definition file looks like:

```
binary darwin-x64 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-darwin-x64.tar.gz#f5768eaabc692fd3ed0cb063d17962c933951b78dec09af3c30eb76c3189d9ee"
binary darwin-x86 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-darwin-x86.tar.gz#b0fe1dc7ed538b14c253de2d3b0bb49317126d0736855f5eed64a79ade99fe4e"
binary linux-x64 "http://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x64.tar.gz#2bc13477684a9fe534bdc9d8f4a8caf6257a11953b57c42cad9b919ee259a0d5"

install_package "node-v0.10.36" "https://nodejs.org/dist/v0.10.36/node-v0.10.36.tar.gz#b9d7d1d0294bce46686b13a05da6fc5b1e7743b597544aa888e8e64a9f178c81"
```

So, `binary {platform} {url}` from the definition file registers the URL if the platform matches. When `install_package` is invoked, it sees that `$BINARY_URL` is set (and if `$SKIP_BINARY` is *not* set via `--compile`) then it sets `$BINARY_ATTEMPT` and calls `install_binary` which is really just a convenience wrapper around `install_package` with some sugar. Any errors during the binary installation will get trapped by `build_failed` which emits the extra help message about the `--compile` flag. If the binary install is successful, then the `$BINARY_ATTEMPT` flag (set when the binary install began) prevents the standard compilation from continuing. (this was the missing piece causing the double-install) If none of the platforms in the original definition file matched, then `$BINARY_URL` would not have been set, so the standard `install_package` flow would proceed as usual.

I think `binary` is a better name than `distro` for all the function and variable names. If this looks good to people, I think we can merge it and have it available for the node 5.0.0 release that just dropped.

**Comment by jawshooah** [comment]
@jasonkarns Thanks for the ping, this is excellent!

**Pull request merged**
